/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{html,js,jsx}"],
  theme: {
    extend: {
      fontFamily: {
        lavishly: ['"Lavishly Yours"', 'cursive'],
        tangerine: ['"Tangerine"', 'cursive'],
        pacifico: ['"Pacifico"', 'cursive'],
        dancing: ['"Dancing Script"', 'cursive'],
        playfair: ['"Playfair Display"', 'serif'],
        roboto: ['"Roboto"', 'sans-serif'],
        montserrat: ['"Montserrat"', 'sans-serif'],
        openSans: ['"Open Sans"', 'sans-serif'],
        raleway: ['"Raleway"', 'sans-serif'],
        poppins: ['"Poppins"', 'sans-serif'],
        lato: ['"Lato"', 'sans-serif'],
        oswald: ['"Oswald"', 'sans-serif'],
        nunito: ['"Nunito"', 'sans-serif'],
        ubuntuMono: ['"Ubuntu Mono"', 'monospace'],
        arial: ['Arial', 'sans-serif'],
        georgia: ['Georgia', 'serif'],
        courierNew: ['"Courier New"', 'monospace'], //good one
        timesNewRoman: ['"Times New Roman"', 'serif'],
        verdana: ['Verdana', 'sans-serif'],
        tahoma: ['Tahoma', 'sans-serif'],
        helvetica: ['Helvetica', 'sans-serif'],
        comicSans: ['"Comic Sans MS"', 'cursive'],
        quicksand: ['"Quicksand"', 'sans-serif'],
        sourceSans: ['"Source Sans Pro"', 'sans-serif'],
        ubuntu: ['"Ubuntu"', 'sans-serif'],
        arimo: ['"Arimo"', 'sans-serif'],
        noto: ['"Noto Sans"', 'sans-serif'],
        merriweather: ['"Merriweather"', 'serif'],
        cabin: ['"Cabin"', 'sans-serif'],
        firaSans: ['"Fira Sans"', 'sans-serif'],
        oxygen: ['"Oxygen"', 'sans-serif'],
        ptSans: ['"PT Sans"', 'sans-serif'],
        exo: ['"Exo"', 'sans-serif'],
        ralewayDots: ['"Raleway Dots"', 'cursive'],
        indieFlower: ['"Indie Flower"', 'cursive'],
        courgette: ['"Courgette"', 'cursive'],
        dancingScript: ['"Dancing Script"', 'cursive'],
        greatVibes: ['"Great Vibes"', 'cursive'],
        allura: ['"Allura"', 'cursive'],
        baloo: ['"Baloo 2"', 'cursive'],
        baloo2: ['"Baloo 2"', 'cursive'],
        baloo3: ['"Baloo 3"', 'cursive'],
        balooTamma: ['"Baloo Tamma 2"', 'cursive'],
        balooTamma2: ['"Baloo Tamma 2"', 'cursive '],
        balooBhai: ['"Baloo Bhai 2"', 'cursive'],
        balooBhai2: ['"Baloo Bhai 2"', 'cursive'],
        balooChettan: ['"Baloo Chettan 2"', 'cursive'],
        balooChettan2: ['"Baloo Chettan 2"', 'cursive'],
        balooPaaji: ['"Baloo Paaji"', 'cursive'],
        balooPaaji2: ['"Baloo Paaji 2"', 'cursive'],
        balooTamma3: ['"Baloo Tamma 3"', 'cursive'],
        balooTamma4: ['"Baloo Tamma 4"', 'cursive'],
        balooBhai3: ['"Baloo Bhai 3"', 'cursive'],
        balooBhai4: ['"Baloo Bhai 4"', 'cursive'],
        balooChettan3: ['"Baloo Chettan 3"', 'cursive'],
        balooChettan4: ['"Baloo Chettan 4"', 'cursive'],
        balooPaaji3: ['"Baloo Paaji 3"', 'cursive'],
        balooPaaji4: ['"Baloo Paaji 4"', 'cursive'],
        balooBhai5: ['"Baloo Bhai 5"', 'cursive'],
        balooBhai6: ['"Baloo Bhai 6"', 'cursive'],
        balooChettan5: ['"Baloo Chettan 5"', 'cursive'],
        herrVonMuellerhoff : ['"Herr Von Muellerhoff"', 'cursive'],
        specialElite: ['"Special Elite"', 'cursive'],
        lobster: ['"Lobster"', 'cursive'],
      },
    },
  },
  plugins: [],
};
